site_name: Ticket Booking Service Documentation
site_description: Documentation as Code for REST API ticket booking service
site_author: Max

theme:
  name: mkdocs

docs_dir: docs

nav:
  - Home: README.md
  - Architecture:
      - SSD: architecture/SSD.md
      - SDD: architecture/SDD.md
      - ISD: architecture/ISD.md
  - Quality:
      - Test Strategy: quality/test-strategy.md
      - Traceability Matrix: quality/traceability-matrix.md
  - Developer:
      - Onboarding: developer/onboarding.md
      - Versioning: versioning.md